import type { EventWizardStepModule } from './types';

// Canonical wizard module map: every step points to an existing editor surface.
export const EVENT_WIZARD_STEP_MODULES: EventWizardStepModule[] = [
  {
    id: 'choose_path',
    labelKey: 'wizard.registry.choosePath',
    required: true,
    paths: ['ai', 'manual'],
    routeSuffix: '/settings',
    reuseTarget: 'settings.event-settings-form',
  },
  {
    id: 'event_details',
    labelKey: 'wizard.registry.eventDetails',
    required: true,
    paths: ['ai', 'manual'],
    routeSuffix: '/settings',
    reuseTarget: 'settings.event-settings-form',
  },
  {
    id: 'distances',
    labelKey: 'wizard.registry.distances',
    required: true,
    paths: ['ai', 'manual'],
    routeSuffix: '/settings',
    reuseTarget: 'settings.event-settings-form',
  },
  {
    id: 'pricing',
    labelKey: 'wizard.registry.pricing',
    required: true,
    paths: ['ai', 'manual'],
    routeSuffix: '/pricing',
    reuseTarget: 'pricing.pricing-tiers-manager',
  },
  {
    id: 'faq',
    labelKey: 'wizard.registry.faq',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/faq',
    reuseTarget: 'faq.faq-manager',
  },
  {
    id: 'waivers',
    labelKey: 'wizard.registry.waivers',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/waivers',
    reuseTarget: 'waivers.waiver-manager',
  },
  {
    id: 'questions',
    labelKey: 'wizard.registry.questions',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/questions',
    reuseTarget: 'questions.questions-manager',
  },
  {
    id: 'policies',
    labelKey: 'wizard.registry.policies',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/policies',
    reuseTarget: 'policies.policies-form',
  },
  {
    id: 'website',
    labelKey: 'wizard.registry.website',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/website',
    reuseTarget: 'website.website-content-editor',
  },
  {
    id: 'add_ons',
    labelKey: 'wizard.registry.addOns',
    required: false,
    paths: ['ai', 'manual'],
    routeSuffix: '/add-ons',
    reuseTarget: 'add-ons.add-ons-manager',
  },
  {
    id: 'publish',
    labelKey: 'wizard.registry.publish',
    required: true,
    paths: ['ai', 'manual'],
    routeSuffix: '/settings',
    reuseTarget: 'settings.visibility-controls',
  },
];
