/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from message namespace directories.
 * To regenerate: pnpm generate:i18n-loaders
 *
 * Generated: 2025-11-25T14:31:01.176Z
 */

import type { AppLocale } from './routing';

export type NamespaceLoader<T> = (locale: AppLocale) => Promise<T>;

// ============================================
// Root Namespace Loaders
// ============================================

export const rootNamespaceLoaders = {
  common: (targetLocale: AppLocale) =>
    import(`@/messages/common/${targetLocale}.json`).then((mod) => mod.default),
  navigation: (targetLocale: AppLocale) =>
    import(`@/messages/navigation/${targetLocale}.json`).then((mod) => mod.default),
  auth: (targetLocale: AppLocale) =>
    import(`@/messages/auth/${targetLocale}.json`).then((mod) => mod.default),
  errors: (targetLocale: AppLocale) =>
    import(`@/messages/errors/${targetLocale}.json`).then((mod) => mod.default),
} satisfies Record<string, NamespaceLoader<unknown>>;

// ============================================
// Component Namespace Loaders
// ============================================

export const componentNamespaceLoaders = {
  errorBoundary: (targetLocale: AppLocale) =>
    import(`@/messages/components/error-boundary/${targetLocale}.json`).then((mod) => mod.default),
  footer: (targetLocale: AppLocale) =>
    import(`@/messages/components/footer/${targetLocale}.json`).then((mod) => mod.default),
  localeSwitcher: (targetLocale: AppLocale) =>
    import(`@/messages/components/locale-switcher/${targetLocale}.json`).then((mod) => mod.default),
  themeSwitcher: (targetLocale: AppLocale) =>
    import(`@/messages/components/theme-switcher/${targetLocale}.json`).then((mod) => mod.default),
} satisfies Record<string, NamespaceLoader<unknown>>;

// ============================================
// Page Namespace Loaders
// ============================================

export const pageNamespaceLoaders = {
  about: (targetLocale: AppLocale) =>
    import(`@/messages/pages/about/${targetLocale}.json`).then((mod) => mod.default),
  contact: (targetLocale: AppLocale) =>
    import(`@/messages/pages/contact/${targetLocale}.json`).then((mod) => mod.default),
  dashboard: (targetLocale: AppLocale) =>
    import(`@/messages/pages/dashboard/${targetLocale}.json`).then((mod) => mod.default),
  events: (targetLocale: AppLocale) =>
    import(`@/messages/pages/events/${targetLocale}.json`).then((mod) => mod.default),
  help: (targetLocale: AppLocale) =>
    import(`@/messages/pages/help/${targetLocale}.json`).then((mod) => mod.default),
  home: (targetLocale: AppLocale) =>
    import(`@/messages/pages/home/${targetLocale}.json`).then((mod) => mod.default),
  news: (targetLocale: AppLocale) =>
    import(`@/messages/pages/news/${targetLocale}.json`).then((mod) => mod.default),
  profile: (targetLocale: AppLocale) =>
    import(`@/messages/pages/profile/${targetLocale}.json`).then((mod) => mod.default),
  results: (targetLocale: AppLocale) =>
    import(`@/messages/pages/results/${targetLocale}.json`).then((mod) => mod.default),
  settings: (targetLocale: AppLocale) =>
    import(`@/messages/pages/settings/${targetLocale}.json`).then((mod) => mod.default),
  signIn: (targetLocale: AppLocale) =>
    import(`@/messages/pages/sign-in/${targetLocale}.json`).then((mod) => mod.default),
  signUp: (targetLocale: AppLocale) =>
    import(`@/messages/pages/sign-up/${targetLocale}.json`).then((mod) => mod.default),
  team: (targetLocale: AppLocale) =>
    import(`@/messages/pages/team/${targetLocale}.json`).then((mod) => mod.default),
} satisfies Record<string, NamespaceLoader<unknown>>;


// ============================================
// Namespace Selection Types
// ============================================

export type NamespaceSelection = {
  base: readonly BaseNamespace[];
  components: readonly ComponentNamespace[];
  pages: readonly PageNamespace[];
};

const DEFAULT_BASE_NAMESPACES = ['common', 'navigation', 'auth', 'errors'] as const;
const DEFAULT_COMPONENT_NAMESPACES = ['errorBoundary', 'footer', 'localeSwitcher', 'themeSwitcher'] as const;
const DEFAULT_PAGE_NAMESPACES = ['about', 'contact', 'dashboard', 'events', 'help', 'home', 'news', 'profile', 'results', 'settings', 'signIn', 'signUp', 'team'] as const;

type BaseNamespace = typeof DEFAULT_BASE_NAMESPACES[number];
type ComponentNamespace = typeof DEFAULT_COMPONENT_NAMESPACES[number];
type PageNamespace = typeof DEFAULT_PAGE_NAMESPACES[number];

export const publicSelection = (pages: string[] = []): NamespaceSelection => ({
  base: DEFAULT_BASE_NAMESPACES,
  components: DEFAULT_COMPONENT_NAMESPACES,
  pages: pages as PageNamespace[],
});

export const protectedSelection = (pages: string[] = []): NamespaceSelection => ({
  base: DEFAULT_BASE_NAMESPACES,
  components: ['themeSwitcher', 'localeSwitcher', 'errorBoundary'],
  pages: pages as PageNamespace[],
});

export const authSelection = (pages: string[] = []): NamespaceSelection => ({
  base: ['common', 'auth', 'errors'],
  components: ['errorBoundary'],
  pages: pages as PageNamespace[],
});


// ============================================
// Auto-Generated Route Namespace Map
// ============================================

export const generatedRouteNamespaceMap: Record<string, NamespaceSelection> = {
  '/': publicSelection(['home']),
  '/about': publicSelection(['about']),
  '/contact': publicSelection(['contact']),
  '/help': publicSelection(['help']),
  '/privacy': publicSelection(),
  '/terms': publicSelection(),
  '/sign-in': authSelection(['signIn']),
  '/sign-up': authSelection(['signUp']),
  '/dashboard': protectedSelection(['dashboard']),
  '/settings': protectedSelection(['settings']),
  '/profile': protectedSelection(['profile']),
  '/results': publicSelection(['results']),
  '/news': publicSelection(['news']),
  '/events': publicSelection(['events']),
} as const;

// ============================================
// Manual Overrides (edit below, regeneration preserves)
// ============================================
// === MANUAL ROUTE OVERRIDES START ===
// Add custom route mappings here - they take precedence over auto-generated ones
// Example: export const manualRouteOverrides: Record<string, NamespaceSelection> = {
//   '/pricing': publicSelection(['pricing']),
// };

// Add custom route mappings here - they take precedence over auto-generated ones
// Example: export const manualRouteOverrides: Record<string, NamespaceSelection> = {
//   '/pricing': publicSelection(['pricing']),
// };

// Add custom route mappings here - they take precedence over auto-generated ones
// Example: export const manualRouteOverrides: Record<string, NamespaceSelection> = {
//   '/pricing': publicSelection(['pricing']),
// };

// Add custom route mappings here - they take precedence over auto-generated ones
// Example: export const manualRouteOverrides: Record<string, NamespaceSelection> = {
//   '/pricing': publicSelection(['pricing']),
// };

// Add custom route mappings here - they take precedence over auto-generated ones
// Example: export const manualRouteOverrides: Record<string, NamespaceSelection> = {
//   '/pricing': publicSelection(['pricing']),
// };

export const manualRouteOverrides: Record<string, NamespaceSelection> = {};
// === MANUAL ROUTE OVERRIDES END ===
