/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from JSON message files.
 * To regenerate: pnpm generate:i18n-types
 *
 * Generated: 2025-11-25T12:36:48.636Z
 */

import { z } from 'zod';

// ============================================
// Root Namespace Schemas
// ============================================

export const commonSchema = z.object({
  loading: z.string(),
  error: z.string(),
  success: z.string(),
  cancel: z.string(),
  save: z.string(),
  delete: z.string(),
  edit: z.string(),
  close: z.string(),
  search: z.string(),
  filter: z.string(),
  sort: z.string(),
  next: z.string(),
  previous: z.string(),
  submit: z.string(),
  brandName: z.string(),
  goHome: z.string(),
  tryAgain: z.string()
}).strict();

export const navigationSchema = z.object({
  home: z.string(),
  about: z.string(),
  contact: z.string(),
  events: z.string(),
  news: z.string(),
  results: z.string(),
  help: z.string(),
  dashboard: z.string(),
  profile: z.string(),
  settings: z.string()
}).strict();

export const authSchema = z.object({
  signIn: z.string(),
  signUp: z.string(),
  signOut: z.string(),
  email: z.string(),
  password: z.string(),
  rememberMe: z.string(),
  forgotPassword: z.string(),
  noAccount: z.string(),
  hasAccount: z.string(),
  createAccount: z.string(),
  welcome: z.string(),
  welcomeBack: z.string()
}).strict();

export const errorsSchema = z.object({
  notFound: z.string(),
  serverError: z.string(),
  unauthorized: z.string(),
  forbidden: z.string(),
  badRequest: z.string(),
  somethingWentWrong: z.string()
}).strict();


// ============================================
// Component Namespace Schemas
// ============================================

export const errorBoundarySchema = z.object({
  error: z.object({
    title: z.string(),
    description: z.string(),
    errorLabel: z.string(),
    digestLabel: z.string()
  }),
  notFound: z.object({
    code: z.string(),
    title: z.string(),
    description: z.string(),
    helpfulLinks: z.string(),
    tips: z.array(z.string()),
    learnAboutUs: z.string()
  }),
  globalError: z.object({
    title: z.string(),
    description: z.string()
  })
}).strict();

export const footerSchema = z.object({
  sections: z.object({
    about: z.string(),
    resources: z.string(),
    legal: z.string(),
    connect: z.string()
  }),
  links: z.object({
    aboutUs: z.string(),
    contact: z.string(),
    helpCenter: z.string(),
    privacy: z.string(),
    terms: z.string()
  }),
  connectText: z.string(),
  copyright: z.string()
}).strict();

export const localeSwitcherSchema = z.object({
  label: z.string(),
  locale: z.string()
}).strict();

export const themeSwitcherSchema = z.object({
  toggleLabel: z.string(),
  light: z.string(),
  dark: z.string(),
  system: z.string()
}).strict();

export const componentsSchema = z.object({
  errorBoundary: errorBoundarySchema,
  footer: footerSchema,
  localeSwitcher: localeSwitcherSchema,
  themeSwitcher: themeSwitcherSchema,
}).strict();


// ============================================
// Page Namespace Schemas
// ============================================

export const aboutSchema = z.object({
  hero: z.object({
    title: z.string(),
    description: z.string()
  }),
  vision: z.object({
    title: z.string(),
    paragraph1: z.string(),
    paragraph2: z.string()
  }),
  whyWeExist: z.object({
    title: z.string(),
    intro: z.string(),
    butText: z.string(),
    problems: z.array(z.string()),
    solution: z.string()
  }),
  whatWeDo: z.object({
    title: z.string(),
    subtitle: z.string(),
    forRunners: z.object({
      title: z.string(),
      features: z.array(z.string())
    }),
    forOrganizers: z.object({
      title: z.string(),
      features: z.array(z.string())
    }),
    tagline: z.string()
  }),
  philosophy: z.object({
    title: z.string(),
    intro: z.string(),
    believeIn: z.string(),
    values: z.array(z.object({
      title: z.string(),
      description: z.string()
    }))
  }),
  mexicanTechnology: z.object({
    title: z.string(),
    subtitle: z.string(),
    weKnow: z.string(),
    knowledge: z.array(z.string()),
    tagline: z.string()
  }),
  commitment: z.object({
    title: z.string(),
    goals: z.array(z.string()),
    mission: z.string(),
    tagline: z.string()
  })
}).strict();

export const contactSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const dashboardSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const eventsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const helpSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const homeSchema = z.object({
  content: z.object({
    placeholder: z.string()
  })
}).strict();

export const newsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const profileSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const resultsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const settingsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const signInSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const signUpSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const teamSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pagesSchema = z.object({
  about: aboutSchema,
  contact: contactSchema,
  dashboard: dashboardSchema,
  events: eventsSchema,
  help: helpSchema,
  home: homeSchema,
  news: newsSchema,
  profile: profileSchema,
  results: resultsSchema,
  settings: settingsSchema,
  signIn: signInSchema,
  signUp: signUpSchema,
  team: teamSchema,
}).strict();


// ============================================
// Combined Messages Schema
// ============================================

export const messagesSchema = z.object({
  common: commonSchema,
  navigation: navigationSchema,
  auth: authSchema,
  errors: errorsSchema,
  components: componentsSchema,
  pages: pagesSchema,
}).strict();

// TypeScript type inferred from schema
export type Messages = z.infer<typeof messagesSchema>;
