/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from JSON message files.
 * To regenerate: pnpm generate:i18n-types
 *
 * Generated: 2025-11-25T15:06:44.706Z
 */

import { z } from 'zod';

// ============================================
// Root Namespace Schemas
// ============================================

export const rootCommonSchema = z.object({
  loading: z.string(),
  error: z.string(),
  success: z.string(),
  cancel: z.string(),
  save: z.string(),
  delete: z.string(),
  edit: z.string(),
  close: z.string(),
  search: z.string(),
  filter: z.string(),
  sort: z.string(),
  next: z.string(),
  previous: z.string(),
  submit: z.string(),
  brandName: z.string(),
  goHome: z.string(),
  tryAgain: z.string()
}).strict();

export const rootNavigationSchema = z.object({
  home: z.string(),
  about: z.string(),
  contact: z.string(),
  events: z.string(),
  news: z.string(),
  results: z.string(),
  help: z.string(),
  dashboard: z.string(),
  profile: z.string(),
  settings: z.string()
}).strict();

export const rootAuthSchema = z.object({
  signIn: z.string(),
  signUp: z.string(),
  signOut: z.string(),
  email: z.string(),
  password: z.string(),
  rememberMe: z.string(),
  forgotPassword: z.string(),
  noAccount: z.string(),
  hasAccount: z.string(),
  createAccount: z.string(),
  welcome: z.string(),
  welcomeBack: z.string()
}).strict();

export const rootErrorsSchema = z.object({
  notFound: z.string(),
  serverError: z.string(),
  unauthorized: z.string(),
  forbidden: z.string(),
  badRequest: z.string(),
  somethingWentWrong: z.string()
}).strict();


// ============================================
// Component Namespace Schemas
// ============================================

export const componentErrorBoundarySchema = z.object({
  error: z.object({
    title: z.string(),
    description: z.string(),
    errorLabel: z.string(),
    digestLabel: z.string()
  }),
  notFound: z.object({
    code: z.string(),
    title: z.string(),
    description: z.string(),
    helpfulLinks: z.string(),
    tips: z.array(z.string()),
    learnAboutUs: z.string()
  }),
  globalError: z.object({
    title: z.string(),
    description: z.string()
  })
}).strict();

export const componentFooterSchema = z.object({
  sections: z.object({
    about: z.string(),
    resources: z.string(),
    legal: z.string(),
    connect: z.string()
  }),
  links: z.object({
    aboutUs: z.string(),
    contact: z.string(),
    helpCenter: z.string(),
    privacy: z.string(),
    terms: z.string()
  }),
  connectText: z.string(),
  copyright: z.string()
}).strict();

export const componentLocaleSwitcherSchema = z.object({
  label: z.string(),
  locale: z.string()
}).strict();

export const componentThemeSwitcherSchema = z.object({
  toggleLabel: z.string(),
  light: z.string(),
  dark: z.string(),
  system: z.string()
}).strict();

export const componentsSchema = z.object({
  errorBoundary: componentErrorBoundarySchema,
  footer: componentFooterSchema,
  localeSwitcher: componentLocaleSwitcherSchema,
  themeSwitcher: componentThemeSwitcherSchema,
}).strict();


// ============================================
// Page Namespace Schemas
// ============================================

export const pageAboutSchema = z.object({
  hero: z.object({
    title: z.string(),
    description: z.string()
  }),
  vision: z.object({
    title: z.string(),
    paragraph1: z.string(),
    paragraph2: z.string()
  }),
  whyWeExist: z.object({
    title: z.string(),
    intro: z.string(),
    butText: z.string(),
    problems: z.array(z.string()),
    solution: z.string()
  }),
  whatWeDo: z.object({
    title: z.string(),
    subtitle: z.string(),
    forRunners: z.object({
      title: z.string(),
      features: z.array(z.string())
    }),
    forOrganizers: z.object({
      title: z.string(),
      features: z.array(z.string())
    }),
    tagline: z.string()
  }),
  philosophy: z.object({
    title: z.string(),
    intro: z.string(),
    believeIn: z.string(),
    values: z.array(z.object({
      title: z.string(),
      description: z.string()
    }))
  }),
  mexicanTechnology: z.object({
    title: z.string(),
    subtitle: z.string(),
    weKnow: z.string(),
    knowledge: z.array(z.string()),
    tagline: z.string()
  }),
  commitment: z.object({
    title: z.string(),
    goals: z.array(z.string()),
    mission: z.string(),
    tagline: z.string()
  })
}).strict();

export const pageContactSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageDashboardSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageEventsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageHelpSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageHomeSchema = z.object({
  content: z.object({
    placeholder: z.string()
  })
}).strict();

export const pageNewsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageProfileSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageResultsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageSettingsSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageSignInSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageSignUpSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pageTeamSchema = z.object({
  title: z.string(),
  description: z.string()
}).strict();

export const pagesSchema = z.object({
  about: pageAboutSchema,
  contact: pageContactSchema,
  dashboard: pageDashboardSchema,
  events: pageEventsSchema,
  help: pageHelpSchema,
  home: pageHomeSchema,
  news: pageNewsSchema,
  profile: pageProfileSchema,
  results: pageResultsSchema,
  settings: pageSettingsSchema,
  signIn: pageSignInSchema,
  signUp: pageSignUpSchema,
  team: pageTeamSchema,
}).strict();


// ============================================
// Combined Messages Schema
// ============================================

export const messagesSchema = z.object({
  common: rootCommonSchema,
  navigation: rootNavigationSchema,
  auth: rootAuthSchema,
  errors: rootErrorsSchema,
  components: componentsSchema,
  pages: pagesSchema,
}).strict();

// TypeScript type inferred from schema
export type Messages = z.infer<typeof messagesSchema>;
