#!/usr/bin/env bash
set -euo pipefail

DEFAULT_PROFILE_DIR="${HOME}/.config/opencode-profiles/rungomx-omo"
DEFAULT_SOURCE_CONFIG="${HOME}/.config/opencode/opencode.json"
PLUGIN_NAME="${OMO_PLUGIN_NAME:-oh-my-openagent@latest}"

usage() {
  cat <<'EOF'
Usage:
  scripts/opencode-omo-profile.sh init [target-dir]
  scripts/opencode-omo-profile.sh run [target-dir] [-- opencode args...]
  scripts/opencode-omo-profile.sh path [target-dir]

Creates and launches an isolated OpenCode profile for oh-my-openagent experiments
without touching ~/.config/opencode/opencode.json.

Environment:
  OPENCODE_SOURCE_CONFIG  Source opencode.json to copy
  OMO_PLUGIN_NAME         Plugin entry to append (default: oh-my-openagent@latest)
EOF
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

write_profile_readme() {
  local target_dir="$1"

  cat > "$target_dir/README.md" <<EOF
# RunGoMX isolated OMO profile

This profile was generated by \

  scripts/opencode-omo-profile.sh

It is intended for safe oh-my-openagent experiments without changing the main
OpenCode config in ~/.config/opencode.

## Launch

OPENCODE_CONFIG_DIR="$target_dir" opencode

## Optional installer step

Run the installer against this profile instead of your default one:

OPENCODE_CONFIG_DIR="$target_dir" npx oh-my-openagent install --no-tui --claude=<yes|no|max20> --openai=<yes|no> --gemini=<yes|no> --copilot=<yes|no>

Add any other provider flags you actually use.

## Safety notes

- This directory may contain copied provider credentials from your source config.
- Do not commit this directory.
- Keep your main profile as the daily driver unless the isolated profile proves stable.
EOF
}

init_profile() {
  local target_dir="${1:-$DEFAULT_PROFILE_DIR}"
  local source_config="${OPENCODE_SOURCE_CONFIG:-$DEFAULT_SOURCE_CONFIG}"

  require_command python3

  if [[ ! -f "$source_config" ]]; then
    printf 'Source config not found: %s\n' "$source_config" >&2
    exit 1
  fi

  mkdir -p "$target_dir"
  cp "$source_config" "$target_dir/opencode.json"

  python3 - "$target_dir/opencode.json" "$PLUGIN_NAME" <<'PY'
import json
import pathlib
import sys

config_path = pathlib.Path(sys.argv[1])
plugin_name = sys.argv[2]

data = json.loads(config_path.read_text())
plugins = data.get("plugin") or []

if not isinstance(plugins, list):
    raise SystemExit("Expected 'plugin' to be an array when present.")

if plugin_name not in plugins:
    plugins.append(plugin_name)

data["plugin"] = plugins
config_path.write_text(json.dumps(data, indent=2) + "\n")
PY

  write_profile_readme "$target_dir"

  printf 'Created isolated profile: %s\n' "$target_dir"
  printf 'Launch with: OPENCODE_CONFIG_DIR="%s" opencode\n' "$target_dir"
}

looks_like_path() {
  local value="$1"
  [[ "$value" == /* || "$value" == ./* || "$value" == ../* || "$value" == ~* ]]
}

run_profile() {
  local target_dir="$DEFAULT_PROFILE_DIR"

  require_command opencode

  if [[ $# -gt 0 && "$1" != "--" ]] && looks_like_path "$1"; then
    target_dir="$1"
    shift
  fi

  if [[ $# -gt 0 && "$1" == "--" ]]; then
    shift
  fi

  if [[ ! -f "$target_dir/opencode.json" ]]; then
    printf 'Profile not initialized: %s\n' "$target_dir" >&2
    printf 'Run: scripts/opencode-omo-profile.sh init %s\n' "$target_dir" >&2
    exit 1
  fi

  OPENCODE_CONFIG_DIR="$target_dir" opencode "$@"
}

print_path() {
  printf '%s\n' "${1:-$DEFAULT_PROFILE_DIR}"
}

command_name="${1:-help}"
shift || true

case "$command_name" in
  init)
    init_profile "${1:-$DEFAULT_PROFILE_DIR}"
    ;;
  run)
    run_profile "$@"
    ;;
  path)
    print_path "${1:-$DEFAULT_PROFILE_DIR}"
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
